apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  # namespace: test
type: Opaque
data:
  access_key: "MTIzNDU2Nzg="
  secret_key: "MTIzNDU2Nzg="
---
apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
spec:
  containers:
    - name: minio
      image: minio/minio:RELEASE.2020-05-08T02-40-49Z
      imagePullPolicy: IfNotPresent
      args:
      - server
      - /data
      env:
      - name: MINIO_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: ceph-secret
            key: access_key
      - name: MINIO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: ceph-secret
            key: secret_key
      readinessProbe:
        httpGet:
          path: /minio/health/ready
          port: 9000
        initialDelaySeconds: 120
        periodSeconds: 20
      livenessProbe:
        httpGet:
          path: /minio/health/live
          port: 9000
        initialDelaySeconds: 120
        periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio
