# IT IS NOT SUITABLE FOR PRODUCTION USE.
# This YAML describes a basic TiDB cluster with minimum resource requirements,
# which should be able to run in any Kubernetes cluster with storage support.
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: pitr-master
spec:
  version: v6.5.0
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  imagePullPolicy: IfNotPresent
  discovery: {}
  helper:
    image: alpine:3.16.0
    imagePullPolicy: IfNotPresent
  pd:
    baseImage: uhub.service.ucloud.cn/pingcap/pd
    maxFailoverCount: 0
    version: v6.5.0
    imagePullPolicy: IfNotPresent
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    baseImage: uhub.service.ucloud.cn/pingcap/tikv
    version: v6.5.0
    imagePullPolicy: IfNotPresent
    maxFailoverCount: 0
    # If only 1 TiKV is deployed, the TiKV region leader 
    # cannot be transferred during upgrade, so we have
    # to configure a short timeout
    evictLeaderTimeout: 1m
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config: |
      [log-backup]
      enable = true 
  tidb:
    baseImage: uhub.service.ucloud.cn/pingcap/tidb
    version: v6.5.0
    imagePullPolicy: IfNotPresent
    maxFailoverCount: 0
    replicas: 1
    service:
      type: ClusterIP
    config: {}
